name: Deploy Angular Application

on:
  push: 
    branches:
      - mean-docker-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build Docker image
        run: docker build -t nihalr2001/adventuretrip-angular-app .
        
      - name: Publish image to Docker Hub
        run: docker push nihalr2001/adventuretrip-angular-app:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull nihalr2001/adventuretrip-angular-app:latest
        
      - name: Delete old container
        run: |
          if [ $(docker ps -aq -f name=angular-app-container) ]; then
            docker rm -f angular-app-container
          fi
        
      - name: Run Docker container
        run: docker run -d -p 4200:80 --name angular-app-container nihalr2001/adventuretrip-angular-app:latest
